services:
  - type: web
    name: agent-vgames-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: STEAM_API_KEY
        sync: false
