services:
  - type: web
    name: agent-vgames-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: STEAM_API_KEY
        sync: false
      - key: BLIZZARD_CLIENT_ID
        sync: false
      - key: BLIZZARD_CLIENT_SECRET
        sync: false
      - key: TWITCH_API_CLIENT_ID
        sync: false
      - key: TWITCH_API_CLIENT_SECRET
        sync: false
      - key: TWITCH_REFRESH_TOKEN
        sync: false
      - key: TWITCH_TOKEN_URL
        sync: false
    healthCheckPath: /health
    # Explicitamente define a porta externa
    httpPort: 80
    # Configurações adicionalais para lidar com timeouts
    plan: starter
    runtime: docker
    disk:
      name: agent-vgames-disk
      mountPath: /opt/render/project/disk
      sizeGB: 1
